### ISSUE TITLE
Typo in description: "strings" instead of "stirngs"

### ISSUE THREAD

**Issue by nwmiller** [braintree/us-bank-account-validator#2]
Typo in description: "strings" instead of "stirngs"
https://github.com/braintree/us-bank-account-validator/blob/7ba8223a5539756f5942aab26e6184612b0fd853/test/account-number.js#L28

**Comment by EvanHahn** [comment]
@nwmiller Good catch! Would you mind opening a pull request to fix this?

**Comment by nwmiller** [comment]
Pull request opened: https://github.com/braintree/us-bank-account-validator/pull/3

**Comment by EvanHahn** [comment]
Thanks for the PR! Merged it.
